name: gem2

description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.5+3
  file_picker: ^10.1.2
  flutter_bloc: ^8.0.1
  provider: ^6.0.0
  flutter_colorpicker: ^1.0.3
  flutter_carousel_widget: ^2.1.2
  shared_preferences: ^2.0.13
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  geolocator: ^13.0.1
  http: ^1.1.0
  permission_handler: ^11.3.1
  country_picker: ^2.0.26
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1

  cupertino_icons: ^1.0.8
  flutter_svg: ^1.0.0  # Add this line (you can check for the latest version)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3
  pinput: ^5.0.0
  get: ^4.6.6
  google_sign_in: ^6.2.1
  firebase_app_check: ^0.3.1+4
  carousel_slider: ^5.0.0
  photo_view: ^0.15.0
  cached_network_image: ^3.4.1
  smooth_page_indicator: ^1.2.0+3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # Android min sdk min:16, default 21

flutter:


  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
