// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq0_hNs7c1wl85RMiQLUbcbLnaPvAShns',
    appId: '1:459906131969:web:bba6065a8f0e80c3b7b800',
    messagingSenderId: '459906131969',
    projectId: 'gem2-9be37',
    authDomain: 'gem2-9be37.firebaseapp.com',
    storageBucket: 'gem2-9be37.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcVomYGdwd6U0DGBm4XpjTnt2S7yWGbe8',
    appId: '1:459906131969:android:07b04caa81ffecbfb7b800',
    messagingSenderId: '459906131969',
    projectId: 'gem2-9be37',
    storageBucket: 'gem2-9be37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDddk4qUtOFpzNdOSqcQJy4Hi24iJxj-Go',
    appId: '1:459906131969:ios:31a4964e1ad8cc1fb7b800',
    messagingSenderId: '459906131969',
    projectId: 'gem2-9be37',
    storageBucket: 'gem2-9be37.firebasestorage.app',
    iosBundleId: 'com.example.gem2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDddk4qUtOFpzNdOSqcQJy4Hi24iJxj-Go',
    appId: '1:459906131969:ios:31a4964e1ad8cc1fb7b800',
    messagingSenderId: '459906131969',
    projectId: 'gem2-9be37',
    storageBucket: 'gem2-9be37.firebasestorage.app',
    iosBundleId: 'com.example.gem2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq0_hNs7c1wl85RMiQLUbcbLnaPvAShns',
    appId: '1:459906131969:web:78c5c6bff63b42bdb7b800',
    messagingSenderId: '459906131969',
    projectId: 'gem2-9be37',
    authDomain: 'gem2-9be37.firebaseapp.com',
    storageBucket: 'gem2-9be37.firebasestorage.app',
  );

}