// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaLLvb2C9tjmLHYEOVynSm9xV6xnKU7Fc',
    appId: '1:1016707959718:android:d9e3d6cec23fdbe8189d67',
    messagingSenderId: '1016707959718',
    projectId: 'goeleventhmileapp',
    storageBucket: 'goeleventhmileapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKMLq0gnBvPwqMUvFOU90nUeE31DsGv1s',
    appId: '1:1016707959718:ios:5645174620d7a1a6189d67',
    messagingSenderId: '1016707959718',
    projectId: 'goeleventhmileapp',
    storageBucket: 'goeleventhmileapp.appspot.com',
    androidClientId: '1016707959718-24dvk342f8c3lck5g7phnvuarsoeg561.apps.googleusercontent.com',
    iosClientId: '1016707959718-sd25gtrle54oo500srnkvhviuolmep3g.apps.googleusercontent.com',
    iosBundleId: 'com.goeleventhmile.biz',
  );

}